<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.minispring</groupId>
        <artifactId>minispring-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>mini-spring-autoconfigure</artifactId>
    <name>mini-spring-autoconfigure</name>
    <description>自动配置：@Conditional 派生 + AutoConfigurationImportSelector + SPI 读取</description>

    <dependencies>
        <dependency>
            <groupId>com.minispring</groupId>
            <artifactId>mini-spring-context</artifactId>
            <version>0.1.0-SNAPSHOT</version>
        </dependency>
        <!-- 仅 demo 需要：用 ConfigFilePropertySourceLoader 加载 application.yml；框架内核条件机制只依赖 core.env.Environment -->
        <dependency>
            <groupId>com.minispring</groupId>
            <artifactId>mini-spring-config</artifactId>
            <version>0.1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>