<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.minispring</groupId>
        <artifactId>minispring-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>mini-spring-aop</artifactId>
    <name>mini-spring-aop</name>
    <description>AOP：切点 / 通知 / 切面 + JDK 动态代理</description>

    <dependencies>
        <dependency>
            <groupId>com.minispring</groupId>
            <artifactId>mini-spring-context</artifactId>
            <version>0.1.0-SNAPSHOT</version>
        </dependency>
        <!-- 自动配置归位：AopAutoConfiguration 需要 @ConditionalOnClass/@ConditionalOnMissingBean 注解 -->
        <dependency>
            <groupId>com.minispring</groupId>
            <artifactId>mini-spring-autoconfigure</artifactId>
            <version>0.1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>